import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"
 
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export const stolovi = {
  stol1: [
    "Duška Žižak",
    "Srđan Žižak",
    "Lucija Žižak",
    "Ema Žižak",
    "Toni Lozančić",
    "Maja Živković",
    "Ivica Lemac",
    "Nevenka Pulfer",
  ],
  stol2: [
    "Igor Sapunar",
    "Ana Sapunar",
    "Ante Vukorepa",
    "Neva Vukorepa",
    "Martina Jerončić",
    "Ivan Jelaska",
    "Luka Dagelić",
    "Ivan Carević",
    "Andrea Carević",
    "Mislav Petričević",
  ],
  stol3: [
    "Stipe Pleština",
    "Tina Pleština",
    "Neno Anić",
    "Doris Topić Anić",
    "Anđelko Šiško",
    "Matijana Šiško",
    "Maja Bačić",
    "Ognjen Bačić",
    "Marko Šunjić",
    "Matea Krilić",
  ],
  stol4: [
    "Dario Šunjić",
    "Ivana Zelić",
    "Andrija Jezidžić",
    "Dragana Jezidžić",
    "Vedran Jurinović",
    "Sanja Jurinović",
    "Jadranko Ratkušić",
    "Ana Ratkušić",
    "Kristian Ratkušić",
    "Željka Ora",
  ],
  stol5: [
    "Aida Božić",
    "Darka Bakotin",
    "Tanja Radeljak",
    "Miro Radeljak",
    "Ines Tudor",
    "Jelena Novokmet",
    "Stipe Mušura - ujac",
    "Joško Mušura",
    "Irena Mušura",
  ],
  stol6: [
    "Miroslav Gaće",
    "Sandra Gaće",
    "Joško Tomičić",
    "Irena Tomičić",
    "Joško Brzica",
    "Gordana Brzica",
    "Silvio Židić",
    "Suzana Židić",
    "Marko Kristić",
    "Danka Kristić",
  ],
  stol7: [
    "Mate Čagalj",
    "Dragica Čagalj",
    "Bernarda Roudi",
    "Srđan Marasović",
    "Neda Šušić",
    "Anka Tomičić",
    "Tomislav Tomičić",
    "Nediljko Milas",
    "Marica Milas",
    "Ljiljana Bernatović Markota",
    "Ivan Markota",
  ],
  stol8: [
    "Josipa Dujmić",
    "Vjeko Kaleb",
    "Petar Ninić",
    "Ante Lozo",
    "Leo Paurević",
    "Anja Plazonić Coulson",
    "Josip Pavelić",
    "Mladen Perhat",
    "Sonja Gaj Perhat",
    "Roberto Družijanić",
    "Marina Družijanić",
  ],
  stol9: [
    "Edi Matić",
    "Gordana Stojnić",
    "Ružica Matić",
    "Alida Bremer",
    "Ali el Baya",
    "Fabian Bremer",
    "Christine Robenek",
    "Leon el Baya",
    "Jennifer Schuster",
  ],
  stol10: [
    "Ana Marija Hasan",
    "Domagoj Bare",
    "Karmen Guć",
    "Duje Guvo",
    "Anamarija Sabljić",
    "Ivan Sabljić",
    "Petar Gabrilo",
    "Marko Kačunko",
    "Jakov Rogulj",
  ],
  stol11: [
    "Iva Popić",
    "Tomo Popić",
    "Ana Popić",
    "Ante Popić",
    "Marta Zlopaša",
    "Jerko Zlopaša",
    "Željka Nosić",
    "Tonči Korčulanin",
    "Mia Korčulanin",
    "Marin Korčulanin",
  ],
  stol12: [
    "Mijo Šuto",
    "Izabela Šuto",
    "Sebastijan Ivanković",
    "Iva Ivanković",
    "Toma Čelar",
    "Mirka Čelar",
    "Petra Čelar",
    "Dorijan Čelar",
    "Marko Puljić",
    "Tina Puljić",
  ],
  stol13: [
    "Frane Čagalj",
    "Adela Markota Čagalj",
    "Jure Čagalj",
    "Eugen Hruška",
    "Marija Hruška",
    "Hrvoje Čagalj",
    "Anja Čagalj",
    "Ana Čagalj",
    "Petar Čagalj",
    "Nina Čagalj",
    "Vito Čagalj",
  ],
  stol14: [
    "Stipe Buljan",
    "Maja Buljan",
    "Kristina Ivanišević",
    "Jere Ivanišević",
    "Petra Rako",
    "Mateo Rako",
    "Tara Rako",
    "Ivan Buljan",
    "Nikolina Buljan",
  ],
  stol15: [
    "Florijan Kordić",
    "Ana Kordić",
    "Davor Duplančić",
    "Ivan Duplančić",
    "Danko Duhović",
    "Igor Zuanić",
    "Marina Zuanić",
    "Ivan Jadrić",
    "Anamarija Jadrić",
  ],
  stol16: [
    "Mia Bakotin",
    "Nika Bakotin",
    "Dino Bakotin",
    "Klara Domina Jurišić Dieterich",
    "Nina Gardašević",
    "Petar Gardašević",
    "Nora Gardašević",
    "Nađa Radović",
    "Duje Radović",
  ],
  stol17: [
    "Goran Čaljkušić",
    "Ivan Kurevija",
    "Šimun Grgat",
    "Marija Čorić",
    "Matea Karadža",
    "Josip Varnica",
    "Toni Pavić",
    "Mislav Bitanga",
    "Jelena Kalpić",
    "Domagoj Kalpić",
    "Viktoria Kalpić",
  ],
  stol18: [
    "Ivica Rakušić",
    "Lucija Rakušić",
    "Ivan Vuković",
    "Leonora Vuković",
    "Toni Čelić",
    "Matea Čelić",
    "Antonio Mikačić",
    "Brane Elpeza",
    "Dario Tepeš",
    "Josipa Tepeš",
  ],
  stol19: [
    "Matea Karoglan",
    "Ivan Karoglan",
    "Mate Tomičić",
    "Ruža Tomičić",
    "Mila Tomičić",
    "Ivan Tomičić",
    "Marijana Oreb",
    "Neven Oreb",
    "Sanja Sulić",
  ],
  stol20: [
    "Mateo Šušić",
    "Antea Jovanović Šušić",
    "Nikolina Šušić",
    "Tomislav Šušić",
    "Margarita Šušić",
    "Mario Celinić",
    "Marko Mlikota",
    "Vanja Mlikota",
    "Stipe Šušić",
    "Ivana Šušić",
  ],
  stol21: [
    "Antonia Pastuović",
    "Petar Pastuović",
    "Matej Pastuović",
    "Josipa Stipanović",
    "Matea Crmarić",
    "Marin Crmarić",
    "Hani Crmarić",
    "Darija Pavela",
    "Frane Pavela",
  ],
  stol22: [
    "Andrija Banović",
    "Ana Banović",
    "Ivan Čorić",
    "Ana Čorić",
    "Joško Kerum",
    "Iva Ivetić Kerum",
    "Ante Budalić",
    "Katarina Budalić",
    "Gordan Boljat",
    "Eli Boljat",
  ],
  stol23: [
    "Kate Gavran",
    "Albin Popov",
    "Blanka Popov",
    "Ana Gavran Džono",
    "Ana Gavran",
    "Dijana Čagalj",
    "Ana Marija Wei",
    "Nicolai Wei",
    "Tonka Lončar",
    "Stipe Lončar",
  ],
  stol24: [
    "Marina Erceg",
    "Ante Erceg",
    "Karla Erceg",
    "Kajo Erceg",
    "Božena Rako",
    "Slavko Rako",
    "Noa Rako",
    "Bruno Doljanin",
    "Antonia Doljanin",
    "Lea Doljanin",
  ],
  stol25: ["Rezervirano za bend"],
  stol26: [
    "Stipe Kristić",
    "Dobrila Kristić",
    "Josipa Kristić",
    "Andrea Kristić",
    "Kristina Kristić",
    "Ivan Kristić",
    "Vedran Kristić",
    "Neda Kristić",
    "Mate Tomičić",
    "Lucija Čagalj",
  ],
  stol27: [
    "Ivo Mušura",
    "Ivana Mušura",
    "Stipe Mušura",
    "Ana Mušura",
    "Igor Mušura",
    "Duje Mušura",
    "Ante Mušura",
    "Hajdi Mušura",
  ],
};

